# Generated by Django 4.1.5 on 2023-01-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_verification_code_alter_tguser_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_id',
            new_name='user',
        ),
    ]
