# Generated by Django 4.1.5 on 2023-01-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_user_id_tguser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user',
            new_name='app_user',
        ),
    ]
