# Generated by Django 4.1.5 on 2023-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_tgstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgstate',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Вне процедуры создания'), (1, 'Выбор не выполнен'), (2, 'Категория выбрана'), (3, 'Заголовок выбран')], default=0),
        ),
    ]
