# Generated by Django 4.1.5 on 2023-02-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_tgstate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgstate',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
