# Generated by Django 4.1.5 on 2023-02-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_tgstate_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgstate',
            old_name='state',
            new_name='step',
        ),
    ]
