# Generated by Django 4.1.5 on 2023-02-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_rename_state_tgstate_step'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tguser',
            unique_together={('tg_user_id', 'tg_chat_id')},
        ),
    ]
